### ISSUE TITLE
Unable to install fasterRaster package using R.4.3.3 on PC

### ISSUE THREAD

**Issue by kbondo1** [adamlilith/fasterRaster#75]
Hi,

I tried installing fasterRaster on a PC with R4.3.3 using the following code:

remotes::install_github('adamlilith/fasterRaster@intuitive_fasterRaster', dependencies = TRUE)

I then received error below. Do you have any suggestions on how to resolve?

Error : in method for 'activeCat<-' with signature 'x="GRaster",value="numeric"':  arguments ('value') after '...' in the generic must appear in the method, in the same place at the end of the argument list
Error: unable to load R code in package 'fasterRaster'
Execution halted
ERROR: lazy loading failed for package 'fasterRaster'

Warning messages:
1: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
3: In i.p(...) :
  installation of package ‘C:/Users/name/AppData/Local/Temp/Rtmpk1ykmO/file16f04aff378e/fasterRaster_8.3.0.7005.tar.gz’ had non-zero exit status

**Comment by adamlilith** [comment]
Thanks for letting me know!  I was not able to recreate the issue, but I believe I have fixed it (details below).

You should be able to successfully install **fasterRaster** from GitHub.  *However*, I have not pushed the fix to the master branch. The reason is because the fixed version depends on a new version of the **omnibus** package, which is not yet on CRAN (they only allow updates once per month, and I already "spent" mine).  So, as of today (May 1st, 2024), you will need to install **fasterRaster** like this:

```
devtools::install_github('adamlilith/omnibus') # latest version pushed to master
devtools::install_github('adamlilith/fasterRaster@intuitive_fasterRaster') # install from dev branch
```

If this does not work, please let me know, as I can't recreate the original issue so wouldn't know if it's really fixed or not.

*Details on the issue in question*: I had mistakenly included `value` in the signature of `activeCat<-`, but only `activeCat<` in **terra** only allows for a signature on `x`. Fix is in **fasterRaster** version 8.3.0.7007.

Thanks again!
A

**Comment by kbondo1** [comment]
Thanks! I tried installing it with the code above, and am still receiving the same error message.

Error : in method for 'activeCat<-' with signature 'x="GRaster"':  arguments ('value') after '...' in the generic must appear in the method, in the same place at the end of the argument list

**Comment by kbondo1** [comment]
I tried it again and received a slightly different error message, which is below.

Error : in method for 'addCats<-' with signature 'x="GRaster",value="data.frame"':  arguments ('value') after '...' in the generic must appear in the method, in the same place at the end of the argument list

**Comment by adamlilith** [comment]
Thank you again for bringing this to my attention!  It *should* install now... 

Fix: Version `8.3.0.7009` in `intuitive_fasterRaster` branch.

**Comment by kbondo1** [comment]
It worked that time! Thanks so much!

**Comment by adamlilith** [comment]
Yes!!!! Thanks for p4ersisting and letting me know each time!
